[program:laravel-serve]
command=php /var/www/artisan serve --host=0.0.0.0 --port=8000
directory=/var/www
autostart=true
autorestart=true
user=www-data
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:laravel-worker]
command=php /var/www/artisan queue:work database --tries=1 --timeout=600 --sleep=3
directory=/var/www
autostart=true
autorestart=true
user=www-data
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
