[program:laravel-serve]
process_name=%(program_name)s
command=php /var/www/artisan serve --host=0.0.0.0 --port=8000
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/serve.log
stopwaitsecs=10
